FROM ubuntu:16.04

MAINTAINER Nomand <iamnomand@gmail.com>

RUN locale-gen en_US.UTF-8
ENV LANG       en_US.UTF-8
ENV LC_ALL     en_US.UTF-8

RUN sed -i 's/http:\/\/archive\.ubuntu\.com\/ubuntu\//http:\/\/mirrors\.aliyun\.com\/ubuntu\//g' /etc/apt/sources.list

RUN export http_proxy=http://duotai:yjvby-mRq@sheraton.h.xduotai.com:23186
RUN export https_proxy=$http_proxy

RUN apt-get update

RUN echo '正在更新系统'
RUN apt-get install -y -q --no-install-recommends \
    apt-transport-https \
    build-essential \
    ca-certificates \
    curl \
    g++ \
    gcc \
    git \
    make \
    sudo \
    wget \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get -y autoclean

RUN echo '正在安装 nodejs'

ENV NODE_VERSION=7

RUN curl -o- https://deb.nodesource.com/setup_$NODE_VERSION.x | bash -       

RUN sudo apt-get install -y nodejs

RUN echo '正在安装 pm2'
RUN sudo npm install pm2 -g -d --registry https://registry.npm.taobao.org

ENV WORK_DIR=/home/blog-stable

RUN echo '正在创建根目录'
RUN mkdir -p $WORK_DIR

WORKDIR $WORK_DIR

RUN echo '正在从GitHub下载代码'
ENV APP_BRANCH_NAME='koa'
RUN git clone -b $APP_BRANCH_NAME --single-branch git://github.com/V-Tom/blog.git $APP_BRANCH_NAME
ENV WORK_DIR=/home/blog-stable/$APP_BRANCH_NAME

COPY ./local.conf.json $WORK_DIR/app/src/config/local.conf.json
COPY ./fullStackFrontPage.json $WORK_DIR/app/src/config/fullStackFrontPage.json

RUN unset http_proxy
RUN unset https_proxy

ENV WORK_DIR=/home/blog-stable/$APP_BRANCH_NAME/app
WORKDIR $WORK_DIR

RUN echo '正在启动服务'
RUN npm i -d --registry=https://registry.npm.taobao.org

CMD ["pm2","startOrRestart","ecosystem.json","--no-daemon"]

EXPOSE 4000

   